apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - event-statistics-config-cm.yaml
  - event-statistics-config-secret.yaml
  - event-statistics-deploy.yaml
  - event-statistics-route.yaml
  - event-statistics-service.yaml
