apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-dev

bases:
  - ../../base/schema-registry
  - ../../base/villains/database
  - ../../base/villains/app
  - ../../base/heroes/database
  - ../../base/heroes/app
  - ../../base/fights/database
  - ../../base/fights/streaming
  - ../../base/fights/app
  - ../../base/battle-ui/app
  - ../../base/event-statistics/app

images:
  - name: fights
    newName: image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/battle-rest-fights
    newTag: dev
  - name: villains
    newName: image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/battle-rest-villains
    newTag: dev
  - name: heroes
    newName: image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/battle-rest-heroes
    newTag: dev
  - name: event-statistics
    newName: image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/battle-event-statistics
    newTag: dev
  - name: battle-ui
    newName: image-registry.openshift-image-registry.svc:5000/superhero-battle-cicd/battle-ui
    newTag: dev