apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio
spec:
  configuration:
    kafkasql:
      bootstrapServers: 'fights-kafka-kafka-bootstrap.superhero-battle-dev.svc:9092'
    persistence: kafkasql