apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-cicd

resources:
  - trigger-template.yaml
  - trigger-binding.yaml
  - event-listener.yaml
  - trigger-route.yaml
